#
# Test site configuration
#
# -- jordan@teddy-net.com
#
# $Id$
#

baseurl       = "http://localhost"
canonifyurls  = true
languageCode  = "en"
title         = "Clean Site Test"
paginate      = 10

[params]
  Title       = "Startbootstrap Clean Blog"
  Description = "Startbootstrap Clean Blog"
# Categories  = "Cat:"
# Tags        = "Tag:"
  DateForm    = "Mon, Jan 2, 2006"
  Author      = "Jordan Hrycaj"
  email       = "jordan@teddy-net.com"
  contact     = "<testmail>@gmail.com"
  Ganalytics  = "XX-00000000-0"

[[params.social]]
  title = "github"
  url = "https://github.com/mjfh"
[[params.social]]
  title = "bitbucket"
  url = "https://bitbucket.org/mjfh"
[[params.social]]
  title = "linkedin"
  url = "http://uk.linkedin.com/in/jordanhrycaj"

[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180

# Local Variables:
# mode: toml
# comment-column: 0
# comment-start: "#"
# End:
