#
# Test site configuration
#
# -- jordan@teddy-net.com
#
# $Id$
#

baseurl       = "http://localhost"
canonifyurls  = true
languageCode  = "en"
title         = "Clean Site Test"
paginate      = 10

[params]
  Title       = "Startbootstrap Clean Blog"
  Description = "Startbootstrap Clean Blog"
  DateForm    = "Mon, Jan 2, 2006"
  Author      = "Jordan Hrycaj"
  email       = "jordan@teddy-net.com"
  contact     = "<testmail>@gmail.com"
  Ganalytics  = "XX-00000000-0"

# [params.debate]
#   provider  = "<your-debate-provider>"
#   forumid   = "<your-forum-id>"
#   script    = "debate"

# HTML <meta> settings
# [params.meta]
#   author      = "Jordan Hrycaj"
#   description = "Startbootstrap Clean Blog"
#   keywords    = "Startbootstrap Clean Blog"

# Custom taxonomy labels
# [params.label]
#   Categories  = "Cat:"
#   Tags        = "Tag:"

# [params.image]
#   home        = "home.png"
#   post        = "post.png"
#   contact     = "contact.png"
#   about       = "about.png"

# [[params.script]]
#   name = "clean-blog.custom"
# [[params.script]]
#   name = "other-custom-script"

[[params.social]]
  title = "github"
  url = "//github.com/mjfh"
[[params.social]]
  title = "bitbucket"
  url = "//bitbucket.org/mjfh"
[[params.social]]
  title = "linkedin"
  url = "//uk.linkedin.com/in/jordanhrycaj"

[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180

# Local Variables:
# mode: toml
# comment-column: 0
# comment-start: "#"
# End:
